import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import BackgroundEffect from "./components/BackgroundEffect";
import Footer from "./components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Header/>

      <BackgroundEffect/>
      <div className="mt-24">
          {children}
      </div>
      
        <Footer/>
      </body>
      
    </html>
  );
}
